### ISSUE TITLE
Android's minimum API levels for arm and x86 have changed to 16

### ISSUE THREAD

**Issue by gmale** [kennytm/rust-ios-android#12]
Support for ICS (Ice Cream Sandwich - Android API 14/15) was removed on 1/30/2018 in [this commit](https://android.googlesource.com/platform/ndk/+/db1b8336b511cd82590c72d10fe56ad05c0ca314%5E%21/) per [this changelog](https://android.googlesource.com/platform/ndk/+/db1b8336b511cd82590c72d10fe56ad05c0ca314/CHANGELOG.md)

arm and x86 now have a minimum API level of 16 instead of 14.

**Comment by gmale** [comment]
PR to address this issue can be found here: https://github.com/kennytm/rust-ios-android/pull/13

**Comment by kennytm** [comment]
(Fixed by #13, thanks!)
