### ISSUE TITLE
Can not run make_standalone_toolchain.py

### ISSUE THREAD

**Issue by huiyujie** [kennytm/rust-ios-android#6]
In the build instruction, Step 3
when I run `./create-ndk-standalone.sh`
it says:

`make_standalone_toolchain.py: error: unrecognized arguments: --unified-headers`

**Comment by kennytm** [comment]
Not reproducible with NDK r15c. Are you using NDK r16?

**Comment by huiyujie** [comment]
@kennytm  the NDK version is 

16.0.4414007 rc2

**Comment by kennytm** [comment]
@huiyujie OK thanks. Does it work if we simply remove the string `--unified-headers` from `create-ndk-standalone.sh`?

**Comment by kennytm** [comment]
Closing, as there is no response from OP and 42fd0fa7f33c58185217f1dcf5ac6511ebc88a62 already removed the `--unified-headers` flag.
